### ISSUE TITLE
stats

### ISSUE THREAD

**Issue by jasonebox** [BaptisteVandecrux/GC-Net-evaluation#11]
I had a look at some stats.

I think I should clone your git and make some modifications that will inform my suggestions below...

Pls. 
1. insert stats tables into report.
2. define night and day in report, no need for all
3. use R instead of R2
4. define ME as "bias"

**Comment by BaptisteVandecrux** [comment]
1. tables are in the report under Analysis/Air temperature
2. `    day = sza<70
    night = sza > 110`
added in the report
3. r and R2 measure the same thing. low priority
4. done
