### ISSUE TITLE
loading gcnet_lib.py

### ISSUE THREAD

**Issue by jasonebox** [BaptisteVandecrux/GC-Net-evaluation#13]
I had a look at codes GC-Net-evaluation.py and gcnet_lib.py

pytablewriter is interesting

also interesting... Please insert instructions in the Readme or inline in the code how to load gcnet_lib.py so that GC-Net-evaluation.py  can use it.

thx,

JEB

**Comment by BaptisteVandecrux** [comment]
gcnet_lib.py is loaded as a library renamed "gnl":
[import gcnet_lib as gnl](https://github.com/BaptisteVandecrux/GC-Net-evaluation/blob/64654fa9cfb2b565d9d483062de7d5f28b6e9055/GC-Net-evaluation.py#L17)
