### ISSUE TITLE
py libs etc

### ISSUE THREAD

**Issue by jasonebox** [BaptisteVandecrux/GC-Net-evaluation#14]
not finding nead_io as a py lib to install

Are these JAWS output?
- 24_east_grip.csv
- 8_dye2.csv

BTW, I think I got sunposition via: "from jaws import sunposition as sunpos

**Comment by BaptisteVandecrux** [comment]
nead_io was developped by Ken: [https://github.com/GEUS-PROMICE/pyNEAD](https://github.com/GEUS-PROMICE/pyNEAD)
Install it with:
```
pip install git+https://github.com/GEUS-PROMICE/pyNEAD.git
```

The GC-Net files are not yet processed by JAWS. These are the file format that will be used by WSL from now on.
I still need to run JAWS for the tilt estimation.

Yes you are right about sunposition.
I'll update the readme with package installation instructions.

**Comment by BaptisteVandecrux** [comment]
[https://github.com/BaptisteVandecrux/GC-Net-evaluation#installation](https://github.com/BaptisteVandecrux/GC-Net-evaluation#installation)

**Comment by mankoff** [comment]
Note that `nead` interface recently changed. Now

```python
import nead
df = nead.read("sample_csv.dsv")
```

**Comment by BaptisteVandecrux** [comment]
Thanks, I've updated my scripts.
I also see that it now outputs directly TA, P and RH in Celsius, hPa, %, which is great.

**Comment by jasonebox** [comment]
Thanks. I pulled the latest, updated nead call per Ken's comment, sunpos is ok but I get a nead.py line 38 error?

runfile('/Users/jason/Dropbox/AWS/GC-Net-evaluation/GC-Net-evaluation_JEB.py', wdir='/Users/jason/Dropbox/AWS/GC-Net-evaluation')
Reloaded modules: gcnet_lib_JEB
24_east_grip.csv
Traceback (most recent call last):

  File "/Users/jason/Dropbox/AWS/GC-Net-evaluation/GC-Net-evaluation_JEB.py", line 107, in <module>
    df_gc = gnl.load_gcnet('24_east_grip.csv')

  File "/Users/jason/Dropbox/AWS/GC-Net-evaluation/gcnet_lib_JEB.py", line 29, in load_gcnet
    df_gc = nead.read('Input/GC-Net/'+filename)

  File "/Users/jeb/anaconda3/envs/s/lib/python3.7/site-packages/nead/nead.py", line 38, in read
    assert(line.split("#")[1].strip() == '[METADATA]')

AssertionError

**Comment by BaptisteVandecrux** [comment]
Should be fixed now. Thanks for the feedback.

**Comment by mankoff** [comment]
Sorry for changes in the NEAD specification. It is in development, but also stabilizing. Major changes like this should not occur much more. To summarize, the header format changed (see new spec at https://github.com/GEUS-PROMICE/NEAD ) and pyNEAD now returns an xarray dataset rather than a pandas dataframe. Xarray has much better support for carrying metadata with it, but you can easily call `df = ds.to_dataframe()` to get a simplistic Pandas view of the data.

**Comment by BaptisteVandecrux** [comment]
Jason, to make it work with the current input files, you can install a previous version of pyNEAD that do work with my scripts.
```
pip uninstall nead

pip install git+https://github.com/GEUS-PROMICE/pyNEAD.git@04af3bc350884cb0f2f5316210bcfd35d5ea7df8
```

When new files, with the latest standards are distributed, then we'll switch back to the latest version of pyNEAD.

**Comment by jasonebox** [comment]
installing the earlier version of nead seemed to work.

I also did a git pull.

I'm running the stuff and would like to do tele session with you Baptiste to further familiarise with what is going on. 

I think you can close this issue now. :-)
