### ISSUE TITLE
Violin plots - > rain plots

### ISSUE THREAD

**Issue by mankoff** [BaptisteVandecrux/GC-Net-evaluation#15]
I saw some violin plots here earlier, I think. Maybe elsewhere? But I think you were generating violin plots. 

Just came across this paper introducing "rain plots" - show more data, give more insight!

Paper: https://wellcomeopenresearch.org/articles/4-63/v1
Code: https://github.com/RainCloudPlots/RainCloudPlots

**Comment by BaptisteVandecrux** [comment]
I removed them because not so useful.
Thanks for the info. The raincloud plot seem to be using the redundant half of the violin for something.
